--  Warning: This lexical scanner is automatically generated by AFLEX.
--           It is useless to modify it. Change the ".Y" & ".L" files instead.


with Ada.Strings.Unbounded;
with CSS.Parser.Parser_Tokens;
package CSS.Parser.Lexer is

   use CSS.Parser.Parser_Tokens;

   function YYLex return Token;

   Current_Comment : Ada.Strings.Unbounded.Unbounded_String;

end CSS.Parser.Lexer;
