description = "Ada CSS library unit tests"
tags = ["css", "parser"]
name = "cssada_tests"
version = "1.0.0"
licenses = "Apache-2.0"
authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["cssada_tests.gpr"]
website = "https://gitlab.com/stcarrez/ada-css"

[[depends-on]]
cssada = "*"
csstools = "*"
utilada_unit = "^2.6.0"

[configuration]
disabled = true

[[pins]]
cssada = { path = '..' }
csstools = { path = '../tools' }
