--  Warning: This file is automatically generated by AYACC.
--           It is useless to modify it. Change the ".Y" & ".L" files instead.
package CSS.Analysis.Parser.Parser is

   error_count : Natural := 0;

   function Parse (Content  : in String) return Integer;

end CSS.Analysis.Parser.Parser;
