--  Warning: This lexical scanner is automatically generated by AFLEX.
--           It is useless to modify it. Change the ".Y" & ".L" files instead.
--  Template: templates/body-lex.adb

with CSS.Analysis.Parser.Parser_Tokens;
package CSS.Analysis.Parser.Lexer is

   use CSS.Analysis.Parser.Parser_Tokens;

   function YYLex return Token;

end CSS.Analysis.Parser.Lexer;
